"use strict";

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert("produks", [
      {
        id_produk: 6,
        nama_produk: "ALCOHOL GEL POLISH CLEANSER GP-CLN01",
        harga: 12500,
        kategori_id: 1,
        status_id: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id_produk: 9,
        nama_produk: "ALUMUNIUM FOIL ALL IN ONE BULAT 23mm IM",
        harga: 1000,
        kategori_id: 2,
        status_id: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id_produk: 11,
        nama_produk: "ALUMUNIUM FOIL ALL IN ONE BULAT 30mm IM",
        harga: 1000,
        kategori_id: 2,
        status_id: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id_produk: 12,
        nama_produk: "ALUMUNIUM FOIL ALL IN ONE SHEET 250mm IM",
        harga: 12500,
        kategori_id: 2,
        status_id: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id_produk: 15,
        nama_produk: "ALUMUNIUM FOIL HDPE/PE BULAT 23mm IM",
        harga: 12500,
        kategori_id: 2,
        status_id: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id_produk: 17,
        nama_produk: "ALUMUNIUM FOIL HDPE/PE BULAT 30mm IM",
        harga: 1000,
        kategori_id: 2,
        status_id: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id_produk: 18,
        nama_produk: "ALUMUNIUM FOIL HDPE/PE SHEET 250mm IM",
        harga: 13000,
        kategori_id: 2,
        status_id: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id_produk: 19,
        nama_produk: "ALUMUNIUM FOIL PET SHEET 250mm IM",
        harga: 1000,
        kategori_id: 2,
        status_id: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id_produk: 22,
        nama_produk: "ARM PENDEK MODEL U",
        harga: 13000,
        kategori_id: 2,
        status_id: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id_produk: 23,
        nama_produk: "ARM SUPPORT KECIL",
        harga: 13000,
        kategori_id: 3,
        status_id: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id_produk: 24,
        nama_produk: "ARM SUPPORT KOTAK PUTIH",
        harga: 13000,
        kategori_id: 2,
        status_id: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id_produk: 26,
        nama_produk: "ARM SUPPORT PENDEK POLOS",
        harga: 13000,
        kategori_id: 3,
        status_id: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id_produk: 27,
        nama_produk: "ARM SUPPORT S IM",
        harga: 1000,
        kategori_id: 2,
        status_id: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id_produk: 28,
        nama_produk: "ARM SUPPORT T (IMPORT)",
        harga: 13000,
        kategori_id: 2,
        status_id: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id_produk: 29,
        nama_produk: "ARM SUPPORT T - MODEL 1 ( LOKAL )",
        harga: 10000,
        kategori_id: 3,
        status_id: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id_produk: 50,
        nama_produk: "BLACK LASER TONER FP-T3 (100gr)",
        harga: 13000,
        kategori_id: 2,
        status_id: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id_produk: 56,
        nama_produk: "BODY PRINTER CANON IP2770",
        harga: 500,
        kategori_id: 4,
        status_id: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id_produk: 58,
        nama_produk: "BODY PRINTER T13X",
        harga: 15000,
        kategori_id: 4,
        status_id: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id_produk: 59,
        nama_produk:
          "BOTOL 1000ML BLUE KHUSUS UNTUK EPSON R1800/R800 - 4180 IM (T054920)",
        harga: 10000,
        kategori_id: 5,
        status_id: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id_produk: 60,
        nama_produk:
          "BOTOL 1000ML CYAN KHUSUS UNTUK EPSON R1800/R800/R1900/R2000 - 4120 IM (T054220)",
        harga: 10000,
        kategori_id: 5,
        status_id: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id_produk: 61,
        nama_produk:
          "BOTOL 1000ML GLOSS OPTIMIZER KHUSUS UNTUK EPSON R1800/R800/R1900/R2000/IX7000/MG6170 - 4100 IM (T054020)",
        harga: 1500,
        kategori_id: 5,
        status_id: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id_produk: 62,
        nama_produk:
          "BOTOL 1000ML L.LIGHT BLACK KHUSUS UNTUK EPSON 2400 - 0599 IM",
        harga: 1500,
        kategori_id: 5,
        status_id: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id_produk: 63,
        nama_produk:
          "BOTOL 1000ML LIGHT BLACK KHUSUS UNTUK EPSON 2400 - 0597 IM",
        harga: 1500,
        kategori_id: 5,
        status_id: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id_produk: 64,
        nama_produk:
          "BOTOL 1000ML MAGENTA KHUSUS UNTUK EPSON R1800/R800/R1900/R2000 - 4140 IM (T054320)",
        harga: 1000,
        kategori_id: 5,
        status_id: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id_produk: 65,
        nama_produk:
          "BOTOL 1000ML MATTE BLACK KHUSUS UNTUK EPSON R1800/R800/R1900/R2000 - 3503 IM (T054820)",
        harga: 1500,
        kategori_id: 5,
        status_id: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id_produk: 66,
        nama_produk:
          "BOTOL 1000ML ORANGE KHUSUS UNTUK EPSON R1900/R2000 IM - 4190 (T087920)",
        harga: 1500,
        kategori_id: 5,
        status_id: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id_produk: 67,
        nama_produk:
          "BOTOL 1000ML RED KHUSUS UNTUK EPSON R1800/R800/R1900/R2000 - 4170 IM (T054720)",
        harga: 1000,
        kategori_id: 5,
        status_id: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id_produk: 68,
        nama_produk:
          "BOTOL 1000ML YELLOW KHUSUS UNTUK EPSON R1800/R800/R1900/R2000 - 4160 IM (T054420)",
        harga: 1500,
        kategori_id: 5,
        status_id: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id_produk: 70,
        nama_produk: "BOTOL KOTAK 100ML LK",
        harga: 1000,
        kategori_id: 2,
        status_id: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id_produk: 72,
        nama_produk: "BOTOL 10ML IM",
        harga: 1000,
        kategori_id: 6,
        status_id: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ]);
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete("produks", null, {});
  },
};
